# Generated by Django 6.0.3 on 2026-03-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcoursemapping', to='course.course')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcoursemapping', to='product.product')),
            ],
            options={
                'db_table': 'product_course_mapping',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'course'), name='unique_product_course')],
            },
        ),
    ]
