# Generated by Django 6.0.3 on 2026-03-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursecertificationmapping', to='certification.certification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursecertificationmapping', to='course.course')),
            ],
            options={
                'db_table': 'course_certification_mapping',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'certification'), name='unique_course_certification')],
            },
        ),
    ]
